import type { TBRow } from "@/store/trialBalance";
import { sumByCategory2, tbScheduleTotals } from "./tbAggregate";
import { summarizeStock, sumLedgerAdjByScheduleHeads, type AccrualEntry, type ClosingStockEntry, type CogsOverride, type DepreciationEntry, type LedgerAdjustment } from "@/store/adjustments";

export type NetProfitInputs = { cyRows: TBRow[]; pyRows: TBRow[]; closingStock: ClosingStockEntry[]; depreciation: DepreciationEntry[]; accruals: AccrualEntry[]; ledgerAdj: LedgerAdjustment[]; cogs: CogsOverride };
export type NetProfitResult = { totalIncCy: number; totalIncPy: number; totalExpCy: number; totalExpPy: number; pbtCy: number; pbtPy: number; taxCy: number; taxPy: number; profitCy: number; profitPy: number };

export function computeNetProfit(p: NetProfitInputs): NetProfitResult {
  const stock = summarizeStock(p.closingStock);
  const depTotal = p.depreciation.reduce((s, d) => s + d.depreciation, 0);
  const prepaid = p.accruals.filter((a) => a.kind === "prepaid").reduce((s, a) => s + a.amount, 0);
  const accrued = p.accruals.filter((a) => a.kind === "accrued").reduce((s, a) => s + a.amount, 0);
  const cy = sumByCategory2(p.cyRows);
  const py = sumByCategory2(p.pyRows);
  const inc = (k: string) => -(cy[k] ?? 0);
  const incPy = (k: string) => -(py[k] ?? 0);
  const exp = (k: string) => cy[k] ?? 0;
  const expPy = (k: string) => py[k] ?? 0;
  const totalIncCy = inc("Revenue from Operations") + inc("Other Income");
  const totalIncPy = incPy("Revenue from Operations") + incPy("Other Income");
  const purchCatCy = exp("Purchase");
  const purchCatPy = expPy("Purchase");
  const invCY = tbScheduleTotals(p.cyRows, ["Inventories"]);
  const invPY = tbScheduleTotals(p.pyRows, ["Inventories"]);
  const openingInvCy = p.cogs.openingInventory ?? Math.round(invCY.opening || invPY.closing || 0);
  const openingInvPy = Math.round(invPY.opening || 0);
  const purchCYTotals = tbScheduleTotals(p.cyRows, ["Purchase of Goods"]);
  const purchPYTotals = tbScheduleTotals(p.pyRows, ["Purchase of Goods"]);
  const purchasesCy = p.cogs.purchases ?? Math.round(purchCYTotals.additions - purchCYTotals.credits || purchCYTotals.closing);
  const purchasesPy = Math.round(purchPYTotals.additions - purchPYTotals.credits || purchPYTotals.closing);
  const tbDirectExpCy = purchCatCy - purchasesCy;
  const directExpCy = p.cogs.directExpenses ?? tbDirectExpCy;
  const directExpPy = purchCatPy - purchasesPy;
  const closingInvCy = stock.good;
  const cogsCy = openingInvCy + purchasesCy - closingInvCy + directExpCy;
  const cogsPy = openingInvPy + purchasesPy + directExpPy;
  const writtenOffCy = stock.expiry + stock.defect;
  const rmAdj = sumLedgerAdjByScheduleHeads(p.ledgerAdj, ["Repair & Maintenance"]);
  const intAdj = sumLedgerAdjByScheduleHeads(p.ledgerAdj, ["Bank Interest", "Interest on Unsecured Loans"]);
  const empCy = exp("Employee Benefit Expense");
  const empPy = expPy("Employee Benefit Expense");
  const finCy = exp("Finance Costs") + intAdj;
  const finPy = expPy("Finance Costs");
  const sellCy = exp("Selling and Distribution Expenses");
  const sellPy = expPy("Selling and Distribution Expenses");
  const adminCy = exp("Administrative Expenses") + rmAdj;
  const adminPy = expPy("Administrative Expenses");
  const otherExpCy = exp("Other Expenses");
  const otherExpPy = expPy("Other Expenses");
  const taxCy = exp("Tax Expense");
  const taxPy = expPy("Tax Expense");
  const totalExpCy = cogsCy + writtenOffCy + empCy + finCy + depTotal + sellCy + adminCy + otherExpCy - prepaid + accrued;
  const totalExpPy = cogsPy + empPy + finPy + sellPy + adminPy + otherExpPy;
  const pbtCy = totalIncCy - totalExpCy;
  const pbtPy = totalIncPy - totalExpPy;
  const profitCy = pbtCy - taxCy;
  const profitPy = pbtPy - taxPy;
  return { totalIncCy, totalIncPy, totalExpCy, totalExpPy, pbtCy, pbtPy, taxCy, taxPy, profitCy, profitPy };
}
